- Silver/Silver3/Solution_1004_벽돌깨기.java
> #1 BOJ 1004

- Silver/Silver3/Boj_1085_직사각형에서탈출.java
> #1 BOJ - 1085

- Silver/Silver3/N2579_S3_Main_TY.java
여기에 설명 써주면 좋을 것 같습니다~~~~~~~~~~
> #1 BOJ_2579_계단오르기

- Silver/Silver3/Main_1463_1로만들기.java
> #1 BOJ - 1463

- Silver/Silver3/BOJ_2579_계단오르기_JH.py
목표지점을 기준으로 점화식을 세웠습니다. 계단의 수가 1인 경우를 고려하지못해서 계속 에러가 났지만 해결했습니다!>!
> #1 BOJ - 2579

- Silver/Silver3/Boj_17626_FourSquares_DS.java
- Silver/Silver3/Boj_2579_계단오르기_DS.java
- 메모리 : 12208kb
- 시간 : 104ms
dp에 필요한 제곱수의 최소 개수를 저장하기 위해 N이 제곱수이면 dp에 1을 저장하고 
아니면 숫자 N보다 작은 제곱수들을 N에서 뺀 나머지 값 중 dp가 최소인 것을 찾아 1을 더해주었습니다.
> #2 BOJ_17626_Four Squares_DS

- Silver/Silver3/BOJ_2579_계단오르기_HS.java
> #1 BOJ_2579_계단오르기_HS

- Silver/Silver2/BOJ_11724_연결요소의개수_TY.java
- 메모리 : 114996KB
- 시간 : 432ms
서로수 집합 연산 활용해서 풀었습니다  
드디어 할 만한 문제가.....😂
> #18 BOJ_11724_연결요소의개수_TY

- Silver/Silver3/BOJ_17626_Four Squares_HS.java
- Silver/Silver3/BOJ_2579_계단오르기_HS.java
- 시간 제한을 봤을 때 dp로 풀어야 할 것 같았는데 점화식 세우는 데 실패함.. -> 블로그 참조^^,,
> #14 BOJ_17626_Four Squares

- Silver/Silver2/BOJ_11724_연결요소의개수_HS.java
- Silver/Silver3/BOJ_17626_Four Squares_HS.java
- Silver/Silver3/BOJ_2579_계단오르기_HS.java
- 같이 연결되어 있는 묶음의 수를 구해야 한다는 것을 파악하고 Union-Find 사용하려고 함
1. Union-Find로 각 요소 별로 최상위 부모를 설정해준 뒤
2. Counter 배열의 최상위 부모 인덱스에 값을 ++해서 표시하고
3. Counter 배열의 값이 0이 아닌 인덱스 수를 파악함!!
> #18 BOJ_11724_연결요소의개수

- Gold/Gold4/BOJ_1043_거짓말_HS.java
- Silver/Silver2/BOJ_11724_연결요소의개수_HS.java
- Silver/Silver3/BOJ_17626_Four Squares_HS.java
- Silver/Silver3/BOJ_2579_계단오르기_HS.java
- 진실을 "공유" 한다는 것에 초점을 맞추고, Union-Find 접목시킴
1. 파티를 순회하면서 진실을 알고 있거나 "공유를 통해" 알게 되는 멤버를 Union을 통해 최상위 부모를 통일하고
2. 통일된 최상위 부모를 knowList라는 이름의 HashMap에 저장
3. 파티를 돌면서 파티 멤버 중 최상위 부모가 knowList에 존재하는지 containsKey를 통해 찾아보고 있으면 break
4. 마지막 멤버까지 찾았는데 없다면 그 파티는 가도 된다는 것이므로 count++ 해줌!
> #22 BOJ_1043_거짓말

- Silver/Silver2/BOJ_11724_연결요소의갯수_SK2.java
- Silver/Silver3/BOJ_2579_계단오르기_SK.java
union-find 를 통해 구했습니다.
마지막에 for문으로 find 숫자 갯수를 구해서 답으로 입력했습니다.
> #22 BOJ_11724_연결요소의갯수_SK

- Gold/Gold4/BOJ_1043_거짓말_SK.java
- Silver/Silver2/BOJ_11724_연결요소의갯수_SK2.java
- Silver/Silver3/BOJ_2579_계단오르기_SK.java
truth가 포함된 모임이 있다면 while문으로 truth 갱신이 안될때까지 truth가 포함된 모임의 각 인원을 truth로 업데이트 해줬습니다.
이후 거짓말이 불가능한 모임의 수를 카운트 한뒤 전체 모임수에서 빼줬습니다.
> #22 BOJ_1043_거짓말_SK

- Gold/Gold4/BOJ_1043_거짓말_TY.java
- Silver/Silver2/BOJ_11724_연결요소의개수_TY.java
진실을 알고 있는 사람들이 순서대로 나오지않고 계속 추가되어 어떤식으로 관리 해야 될지 몰라 이중List로 구현했고 그로 인해 코드가 많이 복잡합니다ㅜㅜ   
형석이형 코드 보니 Union-Find로 풀면 되는 거였는데 저는 어렵게 풀었네염.... #26 
``` List<List<Integer>> list = new LinkedList<List<Integer>>(); ```
이중 List를 구현해 각 모임별 참석 인원 번호를 저장했습니다.
1. 아래와 같이 진실을 알고 있는 사람들 배열을 만들어 해당 인원의 값을 true로 바꿔주었습니다.
``` boolean[] isKnow = new boolean[N+1]; // 진실을 알고 있는 사람들 ```
2. 각 모임별 인원의 정보를 받아 올 때
진실을 아는 사람이 모임에 있는 경우 해당 모임 전체를 isKnow 배열에서 true로 바꿔주었습니다.
진실을 아는 사람이 모임에 없는 경우 list에 모임 전체 정보를 추가했습니다.
3. for문을 돌며
list에 속한 모든 모임 전체 인원이 진실을 모를 때 까지 
isKnow배열과 list를 update해주며 정답을 구했습니다.
> #22 BOJ_1043_거짓말_TY

- Gold/Gold4/BOJ_1043_거짓말_TY.java
- Silver/Silver1/BOJ_9205_맥주마시면서걸어가기_TY.java
- Silver/Silver2/BOJ_11724_연결요소의개수_TY.java
BFS로 이동할 수 있는 곳(1000이내)으로 이동하면서 해결했습니다
```
map.put(nodeX+"."+nodeY, 0);
```
HashMap에서 key값을 nodeX와 nodeY로 구성하고 싶은데 좋은 방법이 있을까요?  
저는 잘 몰라서 nodeX+"."+nodeY로 해결했습니다...ㅜ
> #28 BOJ_9205_맥주마시면서걸어가기_TY

- Gold/Gold4/BOJ_1043_거짓말_HS.java
- Silver/Silver2/BOJ_1012_유기농배추_HS.java
- Silver/Silver2/BOJ_11724_연결요소의개수_HS.java
- Silver/Silver3/BOJ_17626_Four Squares_HS.java
- Silver/Silver3/BOJ_2579_계단오르기_HS.java
- BFS로 배추가 있는 곳들을 탐색하면서 인접한 곳 끼리는 같은 index를 부여
- 마지막에 얻은 index 수가 곧 필요한 지렁이 수!
> BOJ_1012_유기농배추

- Gold/Gold4/BOJ_2636_치즈_HS.java
- Silver/Silver1/BOJ_9205_맥주마시면서걸어가기_HS.java
1. BFS로 가장 바깥 테두리를 찾고 해당 치즈 부분들을 meltList에 담고
2. 다음 시간에 해당 list 돌면서 제거 (= 0)
3. 1, 2번 반복하며 시간체크..^^
> #29 BOJ_2636_치즈_HS

- Silver/Silver1/BOJ_9205_맥주마시면서걸어가기_HS.java
- Silver/Silver2/BOJ_10819_차이를최대로_HS.java
1. map 배열에 현재 이동 가능한지에 대한 정보를 넣어준다.
2. map을 BFS 탐색한다.
- 첫 번째 시작지점(col = 0)의 값을 BFS에 넣고 시작
- map 배열에서 map[col=0][nc]의 값이 1000이하인  nc 값을 queue에 넣어주면서 해당 nc는 방문처리 (nc는 이동가능한 다른 col)
> #28 BOJ_9205_맥주마시면서걸어가기_HS

- Gold/Gold4/BOJ_1043_거짓말_SK.java
- Silver/Silver2/BOJ_1012_유기농배추_SK.java
- Silver/Silver2/BOJ_11724_연결요소의갯수_SK2.java
- Silver/Silver3/BOJ_2579_계단오르기_SK.java
map을 돌며 1인 배추 지역을 bfs로 4방 탐색하여 0으로 만든 뒤 cnt 숫자를 하나씩 늘렸습니다.
> #37 BOJ_1012_유기농배추_SK

- Silver/Silver2/BOJ_11048_이동하기_HS.java
1. 이동할 수 있는 방향이 오른쪽 아래쪽 오른쪽대각선아래 세가지 -> 다시 되짚어가거나 겹치는 부분이 없음
2. 위 조건 때문에 DP로 가능하지 않을까 생각하고 DP로 접근
- i > 0, j > 0 이면 dp[i-1][j-1], dp[i-1][j], dp[i][j-1] 중에서 최대값 + 현재 자리값
- i > 0, j == 0 이면 dp[i-1][j] + 현재 자리값
- i == 0, j > 0 이면 dp[i][j-1] + 현재 자리값
> #41 BOJ_11048_이동하기_HS

- Silver/Silver2/BOJ_10819_차이를최대로_SK.java
순열을 써서 모든 경우의 수를 구한뒤 가장 큰 값을 구했는데..
이거 숫자가 조금만 커도 바로 시간 터질것 같네요ㅠ
list 정렬 후 풀어야 할것 같은데.. 이분 풀이가 괜찮네요
https://www.acmicpc.net/source/26684734
> #40 BOJ_10819_차이를최대로_SK

- Silver/Silver2/BOJ_2579_계단오르기_SK.java
BFS는 방문처리 boolean[] 을 꼭 만드는게 나은것 같습니다..ㅎㅎ
> #41 BOJ_11048_이동하기_SK

- Silver/Silver1/BOJ_9205_맥주마시면서걸어가기_SK.java
BFS로 큐를 만들어 풀었습니다.
최초 start 지점을 큐에 넣고 해당 지점에서 목적지 까지 갈수 있다면 true를 리턴하고 그렇지 않을경우
해당 지점에서 갈수 있는 편의점을 큐에 넣고 다시 목저지 까지 갈수 있는지 확인을 반복했습니다.
> #28 BOJ_9205_맥주마시면서걸어가기_SK

- Silver/Silver3/BOJ_17626_FourSquares_JH.py
> #14 BOJ_17626_Four Squares_JH

- Silver/Silver3/BOJ_2579_계단오르기_TY.java
진짜 개 힘드네....
계단 밟는 경우와 안 밟는 경우 나눠서 구했습니다...
> #1 BOJ_2579_계단오르기_TY

- Gold/Gold4/BOJ_2636_치즈_TY.java
(0,0) 부터 BFS 돌면서 1을 만나는 경우 테두리로 간주하고 0으로 바꾸는 방법으로 반복했습니다.
> #29 BOJ_2606_치즈_TY

- Silver/Silver1/BOJ__1309_동물원_HS.java
- 주석으로 적어뒀지만 간단히 설명하자면,
- dp[n][0] -> 현재 index에서 가능한 case(왼쪽, 오른쪽 케이스가 같아서 하나로 통일)
- dp[n][1] -> 현재 index까지 누적 dp 값
- 내가 세운 점화식은 아래와 같음
1. dp[n][0] = dp[n-1][0] + dp[n-1][1] (이전까지의 누적dp 값 + 그 때 가능한 케이스의 합)
2. dp[n][1] = (dp[n-1][0] * 2 + dp[n-1][1]) % 9901 (이전까지의 누적 dp값 + 그 때 가능한 케이스 (좌, 우) 총 합)
> #54 BOJ_1309_동물원_HS

- Gold/Gold5/BOJ_20055_컨베이어벨트위의로봇_HS.java
1. 컨베이어 벨트의 위치를 바꿔주지 않고, 로봇을 올리는 위치(upIdx)와 내리는 위치(downIdx)를 조절하여 풀었습니다!
2. 로봇의 위치를 저장하기 위한 list와 로봇이 있는 위치를 저장하기 위한 해시맵인 existed를 사용했고
3. 로봇을 올리거나, 로봇이 스스로 이동할 때마다 arr배열의 값을 빼줘서 0이 되면 count++ 해 줬습니다.
> #60 BOJ_20055_컨베이어벨트위의로봇_HS

- Silver/Silver1/BOJ_11052_카드구매하기_HS.java
1. 처음엔 i번 째 카드일 때 P[i]/i 를 이용해서 비율을 구한 뒤 계산하려고 보니 N이 1000이라 너무 오래걸릴 것으로 보였음
2. 뭔가 계속 누적하면서 최대값 구하면 될 것으로 생각되어 DP를 사용함
3. 우선 dp[i] = P[i]로 두고, dp[i-j] + dp[j] (j의 최대값 + (i-j)의 최대값을 하면 i의 최대값일테니)랑 비교해서 갱신함
> #61 BOJ_11052_카드구매하기_HS

- Silver/Silver2/BOJ_1012_유기농배추_TY.java
> Union-Find로 풀었습니다.
2차원 배열이라 기존 1차원 배열로 풀었던 Union-Find를 응용해봤는데 어렵네요ㅜㅜ
> #37 BOJ_1012_유기농배추_TY

- Silver/Silver2/BOJ_1012_유기농배추_JH.py
> #37 BOJ_1012_유기농배추_JH

- Silver/Silver2/BOJ_10819_차이를최대로_TY.java
순열로 해결했습니다! 오랜만에 순열 사용하니 헷갈리네여...ㅋㅋㅋㅋ
순열 생성시 속도를 빠르게 하기 위해 입력 값 정렬  후 가장 큰 값과 가장 작은 값이 제일 앞과 뒤에 오는 경우는 생성하지 않도록 하였습니다!
> #40 BOJ_10819_차이를최대로_TY

- Silver/Silver2/BOJ_11048_이동하기_TY.java
DP를 이용해 현재 값으로 넘어오는 방법 3가지 중(왼쪽에서, 위에서, 왼쪽 위 대각선에서)  
가장 큰 수를 택하는 방식으로 해결했습니다.
```
private static int dp(int x, int y) {
int up = Integer.MIN_VALUE; 
int left = Integer.MIN_VALUE;
int upleft = Integer.MIN_VALUE;
if(candy[x][y] != Integer.MIN_VALUE)
return candy[x][y];
if(x >= 1)
up = dp(x-1,y); // 위에서 오는 경우
if(y >= 1)
left = dp(x,y-1); // 왼쪽에서 오는 경우
if(x >= 1 && y>= 1)
upleft = dp(x-1,y-1); //대각선에서 오는 경우
int temp; // 현재 위치로 넘어오는 방법 중 최대 사탕 개수
temp = Math.max(up, left);
temp = Math.max(temp, upleft);
return candy[x][y] = temp +map[x][y];
}
```
> 기존에 BFS와 DP를 같이 사용해서 풀었는데 아무리해도 시간초과가 나거나 메모리초과가 나서
형석님이랑 세권님 코드 참고해서 해결했습니다!! 감사합니다...ㅜ
> #41 BOJ_11048_이동하기_TY

- Gold/Gold5/BOJ_20055_컴베이어벨트위의로봇_DS.java
- 메모리 : 13448kb
- 속도 : 264ms
벨트 클레스를 만들어서 위에 로봇이 있는지 없는 지와 내구도를 저장했습니다.
> #60 BOJ_20055_컨베이어벨트위의로봇_DS

- Silver/Silver2/BOJ_11725_트리의부모찾기_HS.java
1. ArrayList 배열을 생성해서 양방향 (동적)인접 행렬 만들기
2. 루트 노드(1번)부터 BFS탐색 시작해서, 방문처리하면서 방문
3. 방문 시 현재 좌표 cur 값이 부모 노드, next 값이 자식 노드이므로 parent[next] = cur로 부모 노드 값 저장 후 출력
> #74 BOJ_11725_트리의부모찾기_HS

- Silver/Silver1/BOJ_11052_카드구매하기_SK.java
DP로 풀었습니다!
처음 weight가 1인 경우 최적해를 구하고
2 인 경우, 3인 경우 .. N인 경우까지 이중 for문으로 dp를 구한 뒤 마지막 dp[N] 값을 결과값으로 리턴했습니다
> #61 BOJ_11052_카드구매하기_SK

- Silver/Silver1/BOJ_11502_카드구매하기_DS.java
- 📝 메모리 : 12004kb
-  🏃 속도 : 108ms
그냥 dp로 풀었습니다.. 전꺼 더한거랑 전전꺼 더한거랑 쭉해서 그중 큰값을 dp에 넣어줬습니다.
> #61 BOJ_11052_카드구매하기_DS

- Silver/Silver2/BOJ_11725_트리의부모찾기_SK_s2.java
1. List 에 양방향 간선 정보를 저장
2. parents arr를 따로 만드러 부모 값 저장
3. Queue를 생성하여 최초 node 1부터 탐색하여 parents가 아직 갱신 되지 않은 child 값만 Queue에 넣어서 parents 모두 탐색할동안 BFS 탐색
> #74 BOJ_11725_트리의부모찾기_SK

- Silver/Silver2/BOJ_16953_AB_SK_s2.java
1. Queue 를 사용 안하면 시간 초과가 납니다.. 그렇게 까지 차이 날 일!??
> #75 BOJ_16953_A->B_SK

- Silver/Silver1/BOJ_1325_효율적인해킹_SK_s1.java
이거 O(NM)은 다 똑같은데 내부 코드를 조금만.. 아주 조금만 더 최적화 시키면 시간 초과 안납니다..!
> #76 BOJ_1325_효율적인해킹_SK

- Silver/Silver2/BOJ_11725_트리의부모찾기_JH.java
태윤오빠가 풀었던대로 풀었는데 됐어요.. 뭐가 차이인지 모르겠는데 태윤오빠 이전 코드를 어케 보는지 모르겠넹ㅇ..
> #41 BOJ_11048_이동하기_JH

- Silver/Silver2/BOJ_16953_AtoB_HS.java
> #75 BOJ_16953_AtoB_HS

- Silver/Silver3/BOJ_15650_N과M2_SK_s3.java
> #77 BOJ_1325_N과M(2)_SK

- Silver/Silver1/BOJ_1325_효율적인해킹_HS.java
|메모리|시간|
|---|---|
|301,464kb|7328ms|
1. DFS와 BFS를 이용하여 감염된 컴퓨터를 순차적으로 탐색하면서 카운팅을 진행하면 된다!
2. 마지막에 카운팅 된 정보에서 max를 추출하고, 다시 반복하면서 max랑 일치하는 컴퓨터 번호를 출력하면 끝!
> #76 BOJ_1325_효율적인해킹_HS

- Silver/Silver3/BOJ_15650_N과M(2)_HS.java
|메모리|시간|
|---|---|
|11,512kb|88ms|
- 조합을 출력하면 된다.
> #77 BOJ_15650_N과M(2)_HS

- Silver/Silver3/BOJ_15652_N과M(4)_HS.java
|메모리|시간|
|---|---|
|15,460kb|112ms|
- 중복 조합을 출력하면 된다.
> #87 BOJ_15652_N과M(4)_HS

- Silver/Silver1/BOJ_11052_카드구매하기_TY.java
DP를 이용해 문제를 해결했습니다.
```
int[] DP = new int[N+1];
DP[0] = 0;
DP[1] = list[1];
for (int i = 2; i <= N; i++) {
for (int j = 1; j <= i; j++) {
DP[i] = Math.max(DP[i], DP[i-j] + list[j]);
}
}
```
> #61 BOJ_11052_카드구매하기_TY

- Silver/Silver1/Boj_1309_동물원_DS.java
> #54 BOJ_16953_동물원_DS

- Gold/Gold2/BOJ_2931_가스관_TY.java
기존에 집과 유치원 중 한 곳에서 먼저 통로를 따라 BFS 돌린 뒤 . 을 만난 경우 #으로 변경하고 
나머지 부분에서 BFS 돌린 뒤 #을 만난 경우를 지워진 부분이라고 생각했습니다. 
하지만 결국 가스관을 따라 이동할 수 있는 경우는 한 가지라 집이나 유치원 중 한 곳에서 BFS 돌린 뒤 . 을 만난 경우 
해당 위치에서 사방 탐색을 통해 통로를 찾은 뒤 알맞은 가스관을 골랐습니다.
가스관을 지나갈때 어떤 방향에서 오는지에 따라 조건을 걸어줘야돼 헷갈리고 어려웠습니다ㅜ
100점자 대선이 설명 참고해서 풀었더니 쉽게 해결했습니다....
> #101 BOJ_2931_가스관_TY

- Gold/Gold5/BOJ_21608_상초_SK_g5.java
> #96 BOJ_21608_상어초등학교_SK

- Silver/Silver1/BOJ_1325_효율적인해킹_SH.java
[BOJ 1325 효율적인 해킹](https://www.acmicpc.net/problem/1463)
<br>
- List 자료형의 배열
- BFS
- 그래프
<br>
- 시간: 8,420 ms
- 메모리: 303,844 kb
<br>
<br>
```
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
public class BOJ_1325_효율적인해킹_SH {
static int N, M;
static List<Integer>[] graph;
static boolean[] visited;
static int[] cnt;
StringTokenizer st = new StringTokenizer(br.readLine());
N = Integer.parseInt(st.nextToken());
M = Integer.parseInt(st.nextToken());
graph …
```
> BOJ_1325_효율적인해킹_SH

- Gold/Gold2/BOJ_2931_가스관_SH.java
[BOJ 2931 가스관](https://www.acmicpc.net/problem/2931)
<br>
- BFS
- if문 분기
- 사방 탐색 (BFS말고 블록을 넣을 자리를 구한 후, 그 자리에 대한 사방 탐색)
<br>
- 시간: 76 ms
- 메모리: 11,528 kb
<br>
<br>
```
import java.util.LinkedList;
import java.util.Queue;
public class BOJ_2931_가스관_SH {
static int R, C;
static char[][] board;
static boolean[][] visited;
StringTokenizer st = new StringTokenizer(br.readLine());
R = Integer.parseInt(st.nextToken());
C = Integer.parseInt(st.nextToken());
board = new char[R][C];
visited = new boolean[R][C]; …
```
> #101 BOJ_2931_가스관_SH

- Silver/Silver1/BOJ_1325_효율적인해킹_JH.java
BFS로 풀었습니당
원래 시간초과가 나서 고민했는데
송희랑 비교해보니
저는 신뢰받는 컴터를 인덱스로 하는 어레이배열을 만들었고
송희는 신뢰하는 컴터를 인덱스로 했길래
한번 index와 value만 바꾸어 보았더니 됐어용..
테케차이인듯..?
> BOJ_1325_효율적인해킹_JH

- Gold/Gold2/BOJ_2931_가스관_HS.java
|메모리|시간|
|---|---|
|11,504kb|76ms|
1. 맵의 크기가 최대 25x25기도 했고, M.Z 이런 경우도 있을까봐 M부터 탐색하지 않고,  '.'을 찾아서 사방탐색 진행함!
2. '.'을 만나면 상하좌우를 탐색하여 연결 가능한지 보고, 가능한 경우에는 flag값을 부여함 (상1, 좌2, 하4, 우8)
3. flag 값으로 2군데 or 4군데 방문 가능한지 체크하고 가능하면 해당 좌표에 연결 가능하게 모양 부여
> #101 BOJ_2931_가스관_HS

- Silver/Silver1/Boj_1325_효율적인해킹_DS.java
일반 for문을 향상된 for문으로 바꾸고 전역변수 바꿨더니 풀렸습니다...
> #76 BOJ_1325_효울적인해킹_DS

- Silver/Silver3/BOJ_15650_N과M2_DS.java
순열 고르는 함수에서 오름차순 조건을 맞는 수만 고를수 있게 if를 만들어서 풀었습니다.
> #77 BOJ_1020_N과M(2)_DS

- Gold/Gold2/BOJ_2931_가스관.java
M에서 도로를 따라가면서 .이 나오면 4방향중 이동할 수 있는 도로를 찾아서 4개면 + 아니면 두개의 도로를 이어줄수 있는 도로를 찾았습니다.
> #101 BOJ_2931_가스관_DS

- Silver/Silver3/BOJ_15652_N과M4_DS.java
N과M(2) 에서 중복을 제거하기 위한 isSelected 없애고 크거나 같은 수 추가해줬습니다.
> #87 BOJ_15652_N과M(4)_DS

- Gold/Gold5/BOJ_12865_평범한배낭_SH.java
[BOJ 12865 평범한 배낭](https://www.acmicpc.net/problem/12865)
<br>
- 이차원 DP 배열
- 배낭 문제
- 0-1 냅색 알고리즘
<br>
- 시간: 152 ms
- 메모리: 51,396 kb
<br>
<br>
```
public class BOJ_12865_평범한배낭_SH {
StringTokenizer st = new StringTokenizer(br.readLine());
int N = Integer.parseInt(st.nextToken());
int K = Integer.parseInt(st.nextToken());
int[] W = new int[N];
int[] V = new int[N];
W[i] = Integer.parseInt(st.nextToken());
V[i] = …
```
> #113 BOJ_12865_평범한배낭_SH

- Gold/Gold5/BOJ_21608_상어초등학교_DS.java
모든 빈자리에서 4방탐색으로 빈자리와 좋아하는 친구의 수를 카운트 했습니다.
- 1번 조건에 맞게 좋아하는 친구가 많으면 그 자리를 pX, pY에 저장했습니다.
- 2번 조건에 맞게 좋아하는 친구가 같으면 빈자리의 수가 클 때 그 자리를 pX, pY에 저장했습니다.
- 3번 조건은 for문을 (1,1)부터 돌기 때문에 알아서 됩니다.
⚠️ 처음에 좋아하는 친구가 0이고 빈자리도 0일 때를 생각 못해서 틀렸음ㅠㅠ
> #95 BOJ_21608_상어초등학교_DS

- Gold/Gold5/BOJ_12865_평범한배낭_SK_g5.java
> #113 BOJ_12865_평범한배낭_SK

- Gold/Gold5/BOJ_16234_인구이동_SK_g5.java
bfs 탐색으로 방문 가능한 인접한 나라를 탐색해 주었습니다.
> #118 BOJ_16234_인구이동_SK

- Gold/Gold3/BOJ_20057_마법사상어와토네이도_DS.java
먼저 (1,1)을 만날 때 까지 빙글빙글 도는 for문을 만들었습니다.
diffusion함수에서 문제에 맞게 모래를 확산시켜줬습니다.
> #96 BOJ_20057_마법사상어와토네이도_DS

- Silver/Silver1/BOJ_11052_카드구매하기_JH
DFS로 풀었는데 시간초과나서 DP로 돌렸어용.. 
형석오빠가 그랬는데 DFS로 풀어서 시간초과나는거면 그건 DFS가 아니다 !! 라고 말했는데
이건 무슨 소린지 잘모르겠고 암튼 그래서 시간초과나면 DP로 돌리래요
그래서 바아로 DP로 돌렸습니다
저 Dp잘못해요... 열심히 하겠습니다
> #61 BOJ_11052_카드구매하기_JH

- Silver/Silver2/BOJ_11048_이동하기_SH.java
[BOJ 11048 평범한 배낭](https://www.acmicpc.net/problem/11048)
<br>
- 이차원 DP 배열
- 삼방탐색(?) ([i-1][j], [i][j-1], [i-1][j-1] 에서 최댓값 찾기)
<br>
- 시간: 532 ms
- 메모리: 79,224 kb
<br>
<br>
```
public class BOJ_11048_이동하기_SH {
StringBuilder sb = new StringBuilder();
StringTokenizer st = new StringTokenizer(br.readLine());
int N = Integer.parseInt(st.nextToken());
int M = Integer.parseInt(st.nextToken());
int[][] board = new int[N][M];
int[][] dp = new int[N][M];
st = new …
```
> #41 BOJ_11048_이동하기_SH

- Gold/Gold5/BOJ_12865_평범한배낭_DS.java
최대 무게부터 i번째 물건을 넣었을 때 vs 안 넣었을 때를 비교해서 큰 값을 dp에 저장해줬습니다.
> #113 BOJ_12865_평범한배낭_DS

- Gold/Gold5/BOJ_16928_뱀과사다리게임_JH
Map에 뱀과 사다리를 통한 이동경로를 담고 BFS로 해결했습니다
처음에 계속 틀렸는데 visited처리를 제대로 해주지 않아서였어용..
BFS틀리면 거의 visited 처리 때문인듯 ㅜㅜ
> #66 BOJ_16928_뱀과사다리게임_JH

- Gold/Gold5/BOJ_16234_인구이동_DS.java
class에 좌표, 인구수, 그룹을 저장했습니다. bfs로 연결되있는 나라는 같은 그룹으로 만들어줬습니다.
각 그룹마다 인구수를 더해서 나눠주고 다시 그룹을 초기화 해주면서 반복했습니다.
##성능
> #118 BOJ_16234_인구이동_DS

- Silver/Silver1/BOJ_2468_안전영역_SK_s1.java
최저 높이에서 최고 높이까지 for문을 통해
안전영역의 최댓값을 bfs로 구했습니다.
> 126 BOJ_2468_안전영역_SK

- Silver/Silver2/BOJ_16953_AB_JH
DFS로 풀었습니다!
이경우에는 10^9가 넘어가서 visited배열을 만들경우 메모리 초과가 나서
고민을 해봤는데 방문처리를 안해줘도 되는 경우였습니당
그리고 타입을 long!!으로 해야해요
> #75 BOJ_16953_AB_JH

- Silver/Silver1/BOJ_1629_곱셈_DS.java
> #131 BOJ_1629_곱셈_DS

- Silver/Silver1/BOJ_15565_귀여운 라이언_TY.java
이상하게 풀었습니다..보지마세요...
```
public class Boj_15565 {
BufferedReader in = new BufferedReader(new InputStreamReader(System.in));
StringTokenizer st=null;
st = new StringTokenizer(in.readLine()," ");
int N = Integer.parseInt(st.nextToken());
int K = Integer.parseInt(st.nextToken());
st = new StringTokenizer(in.readLine()," ");
int ryan =1;
int doll = 0;
ArrayList<Integer> pos = new ArrayList<>();
for(int i=0;i<N;i++) {
doll= Integer.parseInt(st.nextToken());
if(doll==ryan) pos.add(i);
}
int len = pos.size();
int min = Integer.MAX_VALUE;
int cal;
if(len<K) System.out.println(-1);
else {
for(int i=0;i<=len-K;i++) {
cal = pos.get(i+K-1)-pos.get(i)+1;
min = min > cal  ? cal:min;
}
if(min == Integer.MAX_VALUE) System.out.println(-1);
else …
```
> #136 BOJ_15565_귀여운 라이언_TY

- Silver/Silver1/BOJ_16918_봄버맨_DS.java
> #133 BOJ_16918_봄버맨_DS

- Silver/Silver3/BOJ_15654_N과M5_SK_s3.java
> #143 BOJ_15654_N과M(5)_SK

- Silver/Silver1/BOJ_16918_봄버맨_SH.java
[BOJ 16918 봄버맨](https://www.acmicpc.net/problem/16918)
<br>
- 구현 (별로 안 빡셈)
- 사방탐색
<br>
- 시간: 684 ms
- 메모리: 142,292 kb
<br>
<br>
터지기 직전(1초 전)의 폭탄을 A로 표시하고, 2초 뒤에 터질 폭탄을 B로 표시하여 구별하였습니다.
- #### 📘 METHOD DESCRIPTION
- changeBomb(): 맨 처음에만 호출되는 메소드로 초기 폭탄(O)들을 A로 표시<br>
- fillBomb(): 빈 칸을 B폭탄으로 채워 넣음<br>
- explodeBomb(): A폭탄의 사방을 터뜨림 (A 주변을 . 으로 바꿈)<br>
- afterExplodeBomb(): A폭탄들은 터진 것이므로 A폭탄들도 . 으로 바꿈<br>
- toResult(): 결과를 출력하기 위한 메소드로 A폭탄과 B폭탄을 모두 O폭탄으로 바꿈
<br>
```
public class BOJ_16918_봄버맨_SH {
static int R, C, S;
static char[][] board;
BufferedReader br = new …
```
> #1108 BOJ_16918_봄버맨_SH

- Silver/Silver1/BOJ_16918_봄버맨_TY.java
> #140 BOJ_16918_봄버맨_TY

- Gold/Gold5/BOJ_16234_인구이동_JH
BFS로 풀었습니다!
한번의 인구이동 시에 여러 군데에서 동시에 이동을 할 수 있다는 점을 생각하지 못하여 몇번 틀렸었습니당..
ArrayList이용해서 이동한 좌표값을 저장하고 한번의 이동을 마칠 때마다 평균값으로 바꾸어주었습니다.
> #1030 BOJ_16234_인구이동_JH

- Gold/Gold5/BOJ_16234_인구이동_TY.java
- BFS를 사용해 국경선을 열 국가들을 찾았습니다.
- BFS를 사용 할 경우 탐색 과정에서 국경선을 연 국가들의 정보를 모두 poll하게 되어 
- 국경선을 연 국가들의 정보가 남아있지 않아 따로 저장할 수 없었습니다. 따라서 Queue를 하나 더 사용해 저장했습니다.
```
package gold5;
import java.util.ArrayDeque;
import java.util.Queue;
public class N16234_Main {
BufferedReader in = new BufferedReader(new InputStreamReader(System.in));
st = new StringTokenizer(in.readLine()," ");
int N = Integer.parseInt(st.nextToken());
int L = Integer.parseInt(st.nextToken());
int R = Integer.parseInt(st.nextToken());
int[][] people = new int[N][N];
st = new …
```
> #118 BOJ_16234_인구이동_TY

- Silver/Silver1/Silver/Silver1/BOJ_16918_봄버맨_JH.java
폭탄 설치 함수와 폭탄 터뜨리는 함수 두개를 구분하여 while문 안에서 반복하였고 N초가 되었을 때 break하여 출력했습니다. 폭탄 터뜨릴때 인접한 곳의 폭탄은 터뜨리되 같은 시점에 설치된 폭탄이라면 터지게 하면 안되네용.!! 난바보
> #133 BOJ_16918_봄버맨_JH.java

- Silver/Silver3/BOJ_15654_N과M(5)_TY.java
- 조합을 활용해서 풀었습니다.
```
private static void comb(int cnt, String result) {
if(cnt == M) {
sb.append(result).append("\n");
return;
}
if(!isSelected[i]) {
isSelected[i] = true;
comb(cnt+1, result+(list[i])+" ");
isSelected[i] = false;
}
}
}
```
> #87 BOJ_15654_N과M(5)_TY

- Silver/Silver1/BOJ_14888_연산자끼워넣기_TY.java
> #141 BOJ_14888_연산자끼워넣기_TY

- Silver/Silver2/BOJ_1780_종이의개수_TY.java
> #137 BOJ_1780_종이의개수_TY

- Silver/Silver3/BOJ_15657_N과M(8)_TY.java
commit message 문제 번호랑 제목을 잘못 썼습니다ㅜㅜ
중복순열로 해결했습니다.
> #158 BOJ_15657_N과M(8)_TY

- Silver/Silver1/BOJ_1932_정수삼각형_SH.java
[BOJ 1932 정수삼각형](https://www.acmicpc.net/problem/1932)
<br>
- dp
- 누적합
<br>
- 시간: 220 ms
- 메모리: 24,672 kb
<br>
<br>
맨 아랫줄부터 위로 올라가며 최댓값이 되는 경우로 dp배열을 갱신해주었습니다.
그렇게 되면 dp[0][0]에 자연스럽게 최대 합이 저장됩니다.
<br>
```
public class BOJ_1932_정수삼각형_SH {
StringBuilder sb = new StringBuilder();
int [][] board = new int[N][N];
int [][] dp = new int[N][N];
for(int i = 0; i < N; i++) {
for(int j = 0; j < i + 1; j++) { …
```
> #156 BOJ_1932_정수삼각형_SH

- Silver/Silver2/BOJ_15666_N과M(12) _TY.java
#161 [N과M(12)] 의 코드 중 순열 부분을 중복 순열로 바꿔주었습니다.
> #163 BOJ_15666_N과M(12) _TY

- Silver/Silver3/BOJ_15654_N과M(5)_SH.py
[BOJ 15654 N과M(5)](https://www.acmicpc.net/problem/15654)
<br>
- 정렬
- 순열
<br>
- 시간: 224 ms
- 메모리: 137,968 kb
<br>
<br>
파이썬의 itertools 라이브러리의 permutations를 이용하면 쉽게 풀 수 있습니다.
이외의 N과 M 문제들 모두 파이썬으로 풀면 숏코딩이 가능합니다.
itertools 라이브러리에서 자주 쓰이는 3가지입니다.
1. permutations(arr, r): arr배열에서 원소 개수가 r개인 **순열** 뽑기
2. combinations(arr, r): arr배열에서 원소 개수가 r개인 **조합** 뽑기
3. combinations_with_replacement(arr, r): arr배열에서 원소 개수가 r개인 **중복 조합** 뽑기
위의 3가지로 N과M문제 모두 다 풀 수 있습니다. (예전에 파이썬으로 다 풀어뒀어서 꿀팁 겸 올립니당 ㅎㅎ..)
사용 방법 예시는 다음과 같습니다.
arr = [1, 2, 3]이라는 배열이 선언되어있을 때,
permu = list(permutations(arr, 2)) 라고 명령문을 치면,
permu에는 [(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)] 가 저장됩니다.
<br>
```
import sys
from itertools import permutations
temp=sys.stdin.readline().split(" ")
N=int(temp[0])
M=int(temp[1]) …
```
> #143 BOJ_15654_N과M(5)_SH

- Silver/Silver3/BOJ_15657_N과M(8)_SH.py
[BOJ 15654 N과M(8)](https://www.acmicpc.net/problem/15657)
<br>
- 정렬
- 중복 조합
<br>
- 시간: 160 ms
- 메모리: 127,368 kb
<br>
<br>
파이썬의 itertools 라이브러리의 combinations_with_replacement를 이용하면 쉽게 풀 수 있습니다.
이외의 N과 M 문제들 모두 파이썬으로 풀면 숏코딩이 가능합니다.
itertools 라이브러리에서 자주 쓰이는 3가지입니다.
1. permutations(arr, r): arr배열에서 원소 개수가 r개인 **순열** 뽑기
2. combinations(arr, r): arr배열에서 원소 개수가 r개인 **조합** 뽑기
3. combinations_with_replacement(arr, r): arr배열에서 원소 개수가 r개인 **중복 조합** 뽑기
위의 3가지로 N과M문제 모두 다 풀 수 있습니다. (예전에 파이썬으로 다 풀어뒀어서 꿀팁 겸 올립니당 ㅎㅎ..)
사용 방법 예시는 다음과 같습니다.
arr = [1, 2, 3]이라는 배열이 선언되어있을 때,
permu = list(permutations(arr, 2)) 라고 명령문을 치면,
permu에는 [(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)] 가 저장됩니다.
<br>
```
import sys
from itertools import combinations_with_replacement
temp=sys.stdin.readline().split(" ")
N=int(temp[0]) …
```
> #158 BOJ_15657_N과M(8)_SH

- Silver/Silver2/BOJ_15663_N과M(9)_SH.py
[BOJ 15663 N과M(9)](https://www.acmicpc.net/problem/15663)
<br>
- 정렬
- 순열
<br>
- 시간: 288 ms
- 메모리: 135,344 kb
<br>
<br>
파이썬의 itertools 라이브러리의 permutations를 이용하면 쉽게 풀 수 있습니다.
이외의 N과 M 문제들 모두 파이썬으로 풀면 숏코딩이 가능합니다.
itertools 라이브러리에서 자주 쓰이는 3가지입니다.
1. permutations(arr, r): arr배열에서 원소 개수가 r개인 **순열** 뽑기
2. combinations(arr, r): arr배열에서 원소 개수가 r개인 **조합** 뽑기
3. combinations_with_replacement(arr, r): arr배열에서 원소 개수가 r개인 **중복 조합** 뽑기
위의 3가지로 N과M문제 모두 다 풀 수 있습니다. (예전에 파이썬으로 다 풀어뒀어서 꿀팁 겸 올립니당 ㅎㅎ..)
사용 방법 예시는 다음과 같습니다.
arr = [1, 2, 3]이라는 배열이 선언되어있을 때,
permu = list(permutations(arr, 2)) 라고 명령문을 치면,
permu에는 [(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)] 가 저장됩니다.
<br>
```
import sys
from itertools import permutations
temp=sys.stdin.readline().split(" ")
N=int(temp[0])
M=int(temp[1]) …
```
> #161 BOJ_15663_N과M(9)_SH

- Silver/Silver2/BOJ_15666_N과M(12)_SH.py
[BOJ 15666 N과M(12)](https://www.acmicpc.net/problem/15666)
<br>
- 정렬
- 중복 조합
<br>
- 시간: 180 ms
- 메모리: 127,920 kb
<br>
<br>
파이썬의 itertools 라이브러리의 combinations_with_replacement를 이용하면 쉽게 풀 수 있습니다.
이외의 N과 M 문제들 모두 파이썬으로 풀면 숏코딩이 가능합니다.
itertools 라이브러리에서 자주 쓰이는 3가지입니다.
1. permutations(arr, r): arr배열에서 원소 개수가 r개인 **순열** 뽑기
2. combinations(arr, r): arr배열에서 원소 개수가 r개인 **조합** 뽑기
3. combinations_with_replacement(arr, r): arr배열에서 원소 개수가 r개인 **중복 조합** 뽑기
위의 3가지로 N과M문제 모두 다 풀 수 있습니다. (예전에 파이썬으로 다 풀어뒀어서 꿀팁 겸 올립니당 ㅎㅎ..)
사용 방법 예시는 다음과 같습니다.
arr = [1, 2, 3]이라는 배열이 선언되어있을 때,
permu = list(permutations(arr, 2)) 라고 명령문을 치면,
permu에는 [(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)] 가 저장됩니다.
<br>
```
import sys
from itertools import combinations_with_replacement
temp=sys.stdin.readline().split(" ")
N=int(temp[0]) …
```
> #163 BOJ_15666_N과M(12)_SH

- Silver/Silver1/BOJ_1890_점프_SH.java
[BOJ 1890 점프](https://www.acmicpc.net/problem/1890)
<br>
- dp
- 이차원 배열
<br>
- 시간: 84 ms
- 메모리: 11,812 kb
<br>
<br>
처음에 문제를 풀었을 때, 90% 정도에서 '틀렸습니다' 를 받았습니다.
주어지는 이차원 배열의 경우 0~9사이의 정수로 구성되어 있지만,
문제를 잘 읽어보면 **'경로의 개수는 2<sup>63</sup>-1보다 작거나 같다.'** 라는 문구가 있는 것을 확인할 수 있습니다.
그래서 dp 배열은 long타입으로 지정해주니 '맞았습니다' 가 떴습니다.
<br>
```
public class BOJ_1890_점프_SH {
int[][] board = new int[N][N];
long[][] dp = new long[N][N];
st = …
```
> #170 BOJ_1890_점프_SH

- Silver/Silver2/BOJ_11053_가장 긴 증가하는 부분 수열 _TY.java
- 맨 처음에는 부분 집합으로 해결해보려했지만 시간초과가 났습니다.
- 이후 DP 말고는 없을 것 같아 DP로 해결해보려고 노력했습니다.
1. 현재 위치(i)보다 배열 index 순서가 앞 쪽이고(작고), 값(arr[j])도 작은 것들 중에 
dp[]값이 가장 큰 것을 골라 현재 dp[i] +1 해서 저장했습니다.
2. 1번에서 해당하는 것이 없는 경우에는 dp[i]에 1을 저장했습니다.
3. 이후 dp 배열 중 가장 큰 값을 출력했습니다.
```
int[] dp = new int [N];
int count = Integer.MIN_VALUE; // 가장 긴 증가하는 부분 수열 개수
int prevMax = Integer.MIN_VALUE;
for (int j = 0; j < i; j++) {
if(arr[j] < arr[i] && dp[j] > prevMax) {
prevMax = dp[j];
}
}
if(prevMax == Integer.MIN_VALUE) // 이전 값들 보다 작은 경우
prevMax = 0;
dp[i] = prevMax+1;
if(dp[i] > count) // 가장 긴 증가하는 부분 수열인 경우
count = dp[i];
}
```
> #157 BOJ_11053_가장 긴 증가하는 부분 수열 _TY

- Silver/Silver2/BOJ_11055_가장큰증가부분수열_SK.java
> #177 BOJ_11055_가장큰증가부분수열_SK

- Silver/Silver3/BOJ_2606_바이러스_SK_s3.java
> #171 BOJ_2606_바이러스_SK

- Silver/Silver2/BOJ_1780_종이의개수_JH.java
함수 두개를 만들어 풀었습니다
문제 이해하는데에 시간이 걸렸습니답 ㅜㅜ
같은 숫자들의 모임을 하나의 단위로 보면 편할 것 같습니다!
> #137 BOJ_1780_종이의개수

- Silver/Silver1/BOJ_1890_점프_TY.java
1. BFS -> 메모리 초과
2. DFS -> 시간 초과
3. DP 
- isVisited[x][y] 은 (x,y) 위치에서 (N-1, N-1)까지 갈 수 있는 경우의 수를 저장했다.
- 이미 방문해서 종점까지 갈 수 있는 경우의 수를 아는 경우 양수의 값을 저장하고있다.(탐방 종료)
> #170 BOJ_1890_점프_TY

- Silver/Silver2/BOJ_11055_가장큰증가부분수열_JH.java
DP이용해서 LIS로 풀었습니답
근데 문제조건에 수열값은 다 양수인데 왜
if(arr[j] < arr[i] && len[i] < len[j]+arr[i])
-> 여기에서 두번째 조건이 없으면 틀릴까요? 다 양수면 DP값은 계속 증가하니까 저 조건은 의미없는거 아닌가 ? ㅜ
> #177 BOJ_11055_가장큰증가부분수열

- Silver/Silver1/BOJ_1890_점프_JH.java
👉 방식 : DP
👉 주의할 점
1. 오른쪽 , 아래로만 갈 수 있으므로 전체 한바퀴만 반복하면됨
2. 현재 지점에서 가능한 경로 수를 계속해서 복사하며 늘려나감(ex: dp[i+size][j] += dp[i][j])
> #170 BOJ_1890_점프

- Silver/Silver2/BOJ_11055_가장큰증가부분수열_SH.java
[BOJ 11055 가장 큰 증가 부분 수열](https://www.acmicpc.net/problem/11055)
<br>
- DP
- 정렬
<br>
- 시간: 108 ms
- 메모리: 12,088 kb
<br>
<br>
숫자들을 저장하는 num 배열과 누적합을 저장하는 sum 배열을 생성합니다.
누적합의 경우 if문을 사용해 자신보다 큰 수가 앞에 있는 경우는 배제하고 합을 더해갑니다.
또, 누적합이 현재 sum 배열에 들어있는 값보다 큰지도 비교해줍니다.
가장 큰 값을 찾아 sum 배열에 넣어주면 됩니다.
마지막으로, sum 배열에서도 가장 큰 값을 찾아야하므로 정렬을 해준 후, 마지막 원소를 출력합니다.
<br>
```
import java.util.Arrays;
public class BOJ_11055_가장큰증가부분수열_SH {
int[] num = new int[N];
int[] …
```
> #177 BOJ_11055_가장큰증가부분수열_SH

- Silver/Silver2/BOJ_11053_가장긴증가하는부분수열_SH.java
[BOJ 11053 가장 긴 증가하는 부분 수열](https://www.acmicpc.net/problem/11053)
<br>
- DP
- 정렬
<br>
- 시간: 100 ms
- 메모리: 12,088 kb
<br>
<br>
숫자들을 저장하는 num 배열과 누적길이를 저장하는 len 배열을 생성합니다.
len 배열의 초기값은 모두 1로 설정해줍니다. (최소 길이는 자기 자신만을 포함하는 1이므로)
누적길이의 경우 if문을 사용해 자신보다 큰 수가 앞에 있는 경우는 배제하고 1을 더해갑니다.
또, 누적길이가 현재 len 배열에 들어있는 값보다 큰지도 비교해줍니다.
가장 큰 값을 찾아 len 배열에 넣어주면 됩니다.
마지막으로, len 배열에서도 가장 큰 값을 찾아야하므로 정렬을 해준 후, 마지막 원소를 출력합니다.
<br>
```
import java.util.Arrays;
public class BOJ_11053_가장긴증가하는부분수열_SH {
int N = …
```
> #157 BOJ_11053_가장긴증가하는부분수열_SH

- Silver/Silver1/BOJ_1946_신입사원_TY.java
1. 완전 탐색 -> 시간 초과
2. 정렬 후 완전 탐색 -> 시간 초과
3. 도저히 풀이 법이 생각 나지 않아 백준 질문을 참고해서 해결!!  
[참고 질문](https://www.acmicpc.net/board/view/9450) -  `면접 등수가 본인보다 높은 서류 등수를 가진 신입사원들의 면접 등수들 중 가장 높은 등수보다 높다`
> #191 BOJ_1946_신입사원_TY

- Silver/Silver1/BOJ_1946_신입사원_JH.java
👉 n이 최대 100000이므로 이중for문은 무조건 시간초과
👉 일단 comparator 이용해서 2차원 배열 정렬
👉 비교해야할 최솟값(나보다 서류등수가 높은 사람들 중에 가장 높은 면접등수)를 갱신해주면서 1차원 for문으로 해결하였습니다
> #191 BOJ_1946_신입사원_JH

- Silver/Silver1/BOJ_1743_음식물피하기_JH.java
> #195 BOJ_1743_음식물피하기

- Silver/Silver1/BOJ_1931_회의실배정_SH.java
[BOJ 1931 회의실 배정](https://www.acmicpc.net/problem/1931)
<br>
- 이차원 배열 정렬
<br>
- 시간: 468 ms
- 메모리: 42,476 kb
<br>
<br>
시작 시간과 종료 시간을 담는 이차원 배열을 생성합니다.
종료 시간을 우선적으로 비교하고, 같을 경우 시작 시간을 비교하도록 Comparator를 오버라이드 해줍니다. 
<br>
```
import java.util.Arrays;
import java.util.Comparator;
public class BOJ_1931_회의실배정_SH {
int[][] time_table = new int[N][2];
int start = …
```
> #197 BOJ_1931_회의실배정_SH

- Silver/Silver2/BOJ_1912_연속합_SH.java
[BOJ 1912 연속합](https://www.acmicpc.net/problem/1912)
<br>
- dp
- 정렬
<br>
- 시간: 276 ms
- 메모리: 22,688 kb
<br>
<br>
숫자들을 입력 받는 arr 배열을 생성합니다.
누적합을 담는 sum 배열을 생성합니다.
sum[0]에는 arr[0]을 담아주고, sum[1] ~ sum[N - 1] 까지는 이전 인덱스의 sum배열에 arr[i]을 더한 값과 그냥 arr[i]의 크기를 비교하여 담아줍니다.
sum 배열을 정렬하여 최댓값을 출력합니다.
<br>
```
import java.util.Arrays;
public class BOJ_1912_연속합_SH {
int[] arr = new int[N];
int[] sum = new int[N];
for …
```
> #203 BOJ_1912_연속합_SH

- Silver/Silver1/BOJ_1743_음식물피하기_DS.java
> #195 BOJ_1743_음식물피하기_DS

- Silver/Silver2/BOJ_1912_연속합_TY.java
1. Sliding Window로 풀고싶었는데 생각 안나서 완전 탐색 했지만 -> 시간초과
2. DP로 풀었다.
```
// 주요 코드 : dp[i] = Math.max(list[i], dp[i-1] + list[i]);
int[] dp = new int[n];
Arrays.fill(dp, Integer.MIN_VALUE);
int maxValue = list[0];
dp[0] = list[0];
for (int i = 1; i < n; i++) {
dp[i] = Math.max(list[i], dp[i-1] + list[i]);
if(maxValue < dp[i])
maxValue = dp[i];
}
```
도저히 내 머리로는 풀 수 없어서 #204 (송희 코드 참고함)ㅜ
> #203 BOJ_1912_연속합_TY

- Silver/Silver1/BOJ_1931_회의실배정_JH.java
- 저 이거 계속 반나절 생각했는데 결국 못했어요,, 결국 힌트 보고 했습니다 ㅜ
👉 문제점 : 회의 시작 시간 기준으로 정렬하니까 2중 for문 써야해서 시간초과나옴
👉 힌트 : 회의 끝 시간 기준으로 정렬 !
👉 알고나니 쉬운.. ㅜ 열심히 해야겠네요
> #197 BOJ_1931_회의실배정

- Silver/Silver2/BOJ_6603_로또_TY.java
- `조합`
보자 마자 조합인거 알아서 `조합`으로 풀었습니다!
> 오랜만에 쉬운 문제 나이스...!
> #207 BOJ_6603_로또_TY

- Silver/Silver2/BOJ_19621_회의실배정2_TY.java
- `다이나믹 프로그래밍 - DP`
- 내일 멀캠에서 작성할게요~
> #200 BOJ_19621_회의실배정2_TY

- Silver/Silver1/BOJ_1743_음식물피하기_SH.java
[BOJ 1743 음식물 피하기](https://www.acmicpc.net/problem/1743)
<br>
- DFS
- 최댓값 찾기
<br>
- 시간: 124 ms
- 메모리: 13,892 kb
<br>
<br>
board 배열과 visited 배열과 선언합니다.
이중 for문을 활용하여 board 배열의 모든 원소마다 DFS를 돌립니다.
이미 visited가 true인 경우는 배제합니다.
DFS 함수를 탈출했다면, 음식물의 크기를 현재까지 저장된 음식물의 최대 크기와 비교합니다.
음식물의 최대 크기를 출력합니다.
<br>
```
public class BOJ_1743_음식물피하기_SH {
static int[][] board;
static int R, C, K;
static boolean[][] visited;
static int max;
static int size;
R = …
```
> #195 BOJ_1743_음식물피하기_SH

- Silver/Silver3/BOJ_11727_타일링2_TY.java
- `다이나믹 프로그래밍 - DP`
- 그려보면 규칙 보여요!
```
// 핵심 코드 dp[i] = (dp[i-1] + 2*dp[i-2])%10007;
for (int i = 1; i <= N; i++) {
if(i==1) {
dp[i] = 1;
continue;
}else if(i==2) {
dp[i] = 3;
continue;
}
dp[i] = (dp[i-1] + 2*dp[i-2])%10007;
}
```
> #212 BOJ_11727_타일링2_TY

- Silver/Silver2/BOJ_1912_연속합_JH.java
👉 DP이용!
👉 최댓값인 Max와 현재 DP값을 비교하는 if문을 현재 DP값을 갱신하는 if문 안에 넣어서 틀렸었다!
> #203 BOJ_1912_연속합_JH

- Silver/Silver1/BOJ_1743_음식물피하기_TY.java
> #195 BOJ_1743_음식물피하기_TY

- Silver/Silver1/BOJ_5014_스타트링크_DS.java
> #194 BOJ_5014_스타트링크_DS

- Silver/Silver4/BOJ_10610_30_TY.java
- `Math(수학)`
- `규칙`만 찾으면 쉬움
- 규칙 : 숫자들의 합이 3의 배수이면 30의 배수이다. 이때, 마지막 자리수에 0도 존재해야됨!
> #219 BOJ_10610_30_TY

- Silver/Silver3/BOJ_11727_타일링2_JH.java
> #212 BOJ_11727_타일링_JH

- Silver/Silver4/BOJ_11656_접미사배열_TY.java
> #223 BOJ_11656_접미사배열_TY

- Silver/Silver1/BOJ_1931_회의실배정_DS.java
> #197 BOJ_1931_회의실배정_DS

- Silver/Silver2/BOJ_1912_연속합_DS.java
> #203 BOJ_1912_연속합_DS

- Silver/Silver3/BOJ_1431_시리얼번호_TY.java
- `정렬(Sort)`
- Collection.sort()사용해서 풀었습니다. Arrays.sort()보다 Collection.sort()가 더 빠르답니다....(물론 상황마다 다름)
`List 만드는 방식 2개 중 어떤게 좋은가요...?`
- List<int> list = new ArrayList();
- List<int> list = new LinkedList();
> #228 BOJ_1431_시리얼번호_TY

- Silver/Silver2/BOJ_2630_색종이접기_TY.java
- `BFS`
- 네모 칸안에서 서로 다른 색이 있는 경우 다음 단게로 넘어갔습니다~
> #230 BOJ_2630_색종이접기_TY

- Silver/Silver2/BOJ_6603_로또_DS.java
> #207 BOJ_6603_로또_DS

- Silver/Silver1/BOJ_9465_스티커_TY.java
- `DP - 다이나믹프로그래밍`
- 2번째 전에서 최대 값과 현재 값 더하기 OR 1번째 전 대각선 값과 현재 값 더하기
```
dp[0][j] = Math.max(dp[1][j-1]+sticker[0][j], Math.max(dp[0][j-2], dp[1][j-2])+sticker[0][j]);
dp[1][j] = Math.max(dp[0][j-1]+sticker[1][j], Math.max(dp[0][j-2], dp[1][j-2])+sticker[1][j]);
```
> #233 BOJ_9465_스티커_TY

- Silver/Silver3/BOJ_9375_패션왕원송희_TY.java
- 조합, 숫자
- (모자 개수+1) * (상의 개수+1) * (신발 개수+1) - 1
> #237 BOJ_9375_패션왕원송희_TY

- Silver/Silver2/BOJ_14620_꽃길_JH.java
👉 브루트포스!
💢 이문제 너무 풀기 싫었음..........진심........................
👿 2일동안 계속 고민했는데 범위가 작아서 그래프탐색 안쓰고 브루트포스로 간단하게 풀면되겠거니해서 5개 영역의 합이 가장 작은 것부터 더하면서 3번 돌리자! 했는데 채점14%에서 실패..
가장 작은것부터 더한다해서 3개 꽃밭의 합이 최소일거라는 보장이 없어서 틀림 ㅜ
그래서 빡쳐서 그냥 힌트보고품
✏️ for문 3개 돌리면서 꽃을 심을 3개의 영역을 일일히 다 받아서 서로 충돌하지 않으면서, 3개 영역의 합이 최소인지 계속해서 갱신해주는 방식으로 풀었습니다.
> #214 BOJ_14620_꽃길_JH

- Silver/Silver2/BOJ_1500_최대곱_SH.java
[BOJ 1500 최대곱](https://www.acmicpc.net/problem/1500)
<br>
- 규칙 찾기
<br>
- 시간: 76 ms
- 메모리: 11,508 kb
<br>
<br>
곱이 최대가 되려면 S를 K로 나눈 수와 그 수랑 1차이 나는 수들로만 구성되면 됩니다.
이 규칙을 발견하면 코드로 작성하는 것은 쉽습니다.
<br>
```
public class BOJ_1500_최대곱_SH {
long S = Integer.parseInt(st.nextToken());
long K = Integer.parseInt(st.nextToken());
long divNum = S / K;
long restNum = S - (divNum * K);
long answer = 1;
for (long i = 0; i < K - restNum; i++) {
answer *= divNum;
} …
```
> #241 BOJ_1500_최대곱_SH

- Silver/Silver5/BOJ_4673_셀프넘버_SH.java
[BOJ 4673 셀프 넘버](https://www.acmicpc.net/problem/4673)
<br>
- 완전 탐색
<br>
- 시간: 120 ms
- 메모리: 12,272 kb
<br>
<br>
10,000까지의 숫자가 셀프 넘버인지 아닌지를 저장하는 boolean형 배열을 생성해줍니다.
크기는 10,001로 하였습니다.(1~10,000을 체크하기 위해)
셀프 넘버인지 아닌지를 체크하는 check 함수를 만들어줍니다.
check 함수는 문제에 쓰인 조건 그대로를 코드로 옮기면 됩니다.
<br>
```
public class BOJ_4673_셀프넘버_SH {
public static void main(String[] args) {
boolean[] isSelfNum = new boolean[10001];
for (int i = 1; i < 10001; i++) {
int temp = check(i);
if (temp < 10001) {
isSelfNum[temp] = true;
}
}
for (int i = 1; i < 10001; i++) {
if (!isSelfNum[i]) {
System.out.println(i);
}
}
}
static int check(int N) {
int sum = N;
while (N > 0) {
sum += N % 10;
N /= 10;
}
return sum;
}
}
```
> #245 BOJ_4673_셀프넘버_SH

- Silver/Silver4/BOJ_11656_접미사배열_DS.java
> #223 BOJ_11656_접미사배열_DS

- Silver/Silver2/BOJ_1058_친구_JH.java
👉 사용된 알고리즘
- BFS
- 플로이드워셜로 푸는거같은데 전 잘멀라서 걍 BFS로 깊이 2인거까지만 탐색하게 해서 풀었슴둥~
👉 헷갈렸던 점
- 입력받을 때 어케 받아야될지 헷갈렸어용 ,, Y가 뭔가했음
> #246 BOJ_1058_친구_JH

- Silver/Silver4/BOJ_10610_30_JH.java
- 3의 배수인지 확인 : 각자릿수 더해서 3
- 10의 배수 : 끝자리 0
- 맨 앞 자리 0아닌지 확인
👉 위 3가지 조건 다 만족시 30이면서 가장 큰수!
첨엔 30의 배수중에 가장 큰수인줄알고 조합으로 일일히 짜맞춰야하는줄..?
> #219 BOJ_10610_30_JH

- Silver/Silver2/BOJ_2630_색종이_DS.java
> #230 BOJ_2630_색종이접기_DS

- Silver/Silver3/BOJ_1431_시리얼번호_JH.java
> #228 BOJ_1431_시리얼번호_JH

- Silver/Silver2/BOJ_2630_색종이만들기_JH.java
> #230 BOJ_2630_색종이접기_JH

- Silver/Silver2/BOJ_11725_트리의부모찾기_JH2.java
> #232 BOJ_11725_트리의부모찾기_JH2

- Silver/Silver5/BOJ_1343_폴리오미노_DS.java
> #251 BOJ_1343_폴리오미노_DS

- Gold/Gold4/BOJ_9663_Nqueen_JH.java
- 백트래킹인건 기억나는데 음.. 한참 헤매다가 참고해서 풀었숩니다..
- 2차원배열로 하면 넘 어려ㅇ.. 1차원배열로 풀장!!
> #235 BOJ_9663_NQueen_JH

- Silver/Silver3/BOJ_9375_패션왕원송희_JH.java
- HashMap이용했습니다
- 각각 옷종류의 가짓수를 구해서 +1을 해주고(안입을경우), 모두 곱해서 -1을 해주었습니다(알몸).
> #237 BOJ_9375_패션왕원송희_JH

- Silver/Silver2/BOJ_1500_최대곱_JH.java
> #241 BOJ_1500_최대곱_JH

- Silver/Silver2/BOJ_16953_AB_JH.java
> #244 BOJ_16953_AB_JH

- Gold/Gold4/BOJ_9663_NQueen_DS.java
> #235 BOJ_9663_NQueen_DS

- Silver/Silver5/BOJ_1343_폴리오미노_JH.java
> #251 BOJ_1343_JH

- Silver/Silver2/BOJ_1500_최대 곱_TY.java
송희 코드 참고했더니 최대 곱을 구하는 방식이 있었음...ㅜ
엄청 오랜만에 풀었네.....ㅜ
> #241 BOJ_1500_최대 곱_TY

- Silver/Silver3/BOJ_9375_패션왕원송히_DS.java
> #237 BOJ_9663_패션왕원송히_DS

- Gold/Gold2/BOJ_11444_피보나치 수 6_TY.java
> 예찬이형 도움 받음;;; 개어렵네;;; 이 문제;;;;
- 피보나치 수 배열로 구하기
- 배열의 곱 빠르게 하기
- "^n"을 배열의 n승이라 할 경우 아래와 같이 구한다.
ex) ^10 = ^5 * ^5
^5 = ^2 * ^2 * ^1
> #239 BOJ_11444_피보나치 수 6_TY

- Silver/Silver2/BOJ_1500_최대곱_DS.java
> #241 BOJ_1500_최대곱_DS

- Gold/Gold5/BOJ_2096_내려가기_JH.java
> #252 BOJ_2096_내려가기_JH

- Gold/Gold5/BOJ_1107_리모컨_JH.java
- 처음엔 각 번호마다 가장 가까운 번호를 찾는 DFS를 이용하려했지만 100일경우 0과 1이 망가진다면 211 이 아니라 99를 선택해야하기때문에 포기
- 브루트포스로 일일히 다 돌려보는 방식으로 풀었따
> #256 BOJ_1107_리모컨_JH

- Silver/Silver1/BOJ_1991_트리 순회_TY.java
- 트리
- 재귀
> 저는 이진트리 2차원배열로 구성했는데 일차원배열로 구성하는 방식이 더 좋을 것 같습니다...!
> #243 BOJ_1991_트리 순회_TY

- Silver/Silver1/BOJ_1991_트리순회_JH.java
> #243 BOJ_1991_트리순회_JH

- Gold/Gold5/BOJ_13549_숨바꼭질_JH.java
- 0-1 BFS or 다익스트라
- 0-1BFS를 선택해서 Deque를 이용하여 가중치가 0이면 addFront(), 1이면 addLast()로 넣어주었다
- PQ를 사용한다면 if문의 갱신조건 대신 visited로 대체할 수 있어서 더 좋을거같다..
- 배열을 사용하지않고 인자로 넘기는게 나을듯
> #278 BOJ_13549_숨바꼭질_JH

- Silver/Silver5/BOJ_4673_셀프넘버_DS.java
그냥 풀었습니다~~~~~~~~~~~~~~~~~~~~~~~~~~
> #245 BOJ_4673_셀프넘버_DS

- Silver/Silver1/BOJ_2531_회전초밥_JH.java
- 문제에서 1번원칙을 따를경우 쿠폰 초밥 1개를 무료로 제공한다고 되어있는데, 회전벨트 위에 없는 초밥일 경우만 무료 제공인 줄 알고 뻘짓했어용 ㅜ
> #280 BOJ_2531_회전초밥_JH

- Gold/Gold5/BOJ_2096_내려가기_DS.java
> #252 BOJ_2096_내려가기_DS

- Silver/Silver3/BOJ_9461_파도반수열_JH.java
- DP
- 초항을 5항까지 잡아줌
- int 말고 long타입으로 해야됨........
> #283 BOJ_9461_파도반수열_JH

- Gold/Gold5/BOJ_1107_리모컨_DS.java
위아래로 고장난 버튼 제외하고 가장 가까운 숫자 찾아서 떠났습니다
> #256 BOJ_1107_리모콘_DS

- Gold/Gold5/BOJ_13549_숨바꼭질3_DS.java
> #278 BOJ_13549_숨바꼭질_DS

- Gold/Gold2/BOJ_1202_보석도둑_DS.java
> #287 BOJ_1202_보석도둑_DS

- Gold/Gold2/BOJ_1202_보석도둑_JH.java
답 long으로 해야대염................,,,,,,,,........
> #287 BOJ_1202_보석도둑_JH

- Gold/Gold5/BOJ_1916_최소비용구하기_DS.java
> #292 BOJ_1916_최소비용구하기_DS

- Silver/Silver3/BOJ_2407_조합_JH.java
> #288 BOJ_2407_조합_JH
